[build]
  command = "NODE_OPTIONS=--max_old_space_size=4096 pnpm run build"
  publish = "build/client"
  base = "/"

[build.environment]
  NODE_VERSION = "18.18.0"
  NODE_OPTIONS = "--max_old_space_size=4096"
  PNPM_VERSION = "9.4.0"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[plugins]]
  package = "@netlify/plugin-nextjs" 