[build]
  command = "rm -rf node_modules && NODE_OPTIONS=--max_old_space_size=4096 pnpm install --no-frozen-lockfile && pnpm run build && ls -la build/client && cp -r public/* build/client/"
  publish = "build/client"
  base = "/"

[build.environment]
  NODE_VERSION = "18.18.0"
  NODE_OPTIONS = "--max_old_space_size=4096"
  PNPM_VERSION = "9.4.0"
  PNPM_STORE_DIR = "/opt/build/.pnpm-store"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:; img-src 'self' https: data:; font-src 'self' https: data:;" 